# Generated by Django 4.2.4 on 2023-08-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LoanField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("date", "date"),
                            ("email", "email"),
                            ("tel", "tel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("document", models.CharField(max_length=100)),
                (
                    "approved",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("pending", "pending"),
                            ("denied", "denied"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "auto_approved",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("pending", "pending"),
                            ("denied", "denied"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "custom_fields",
                    models.ManyToManyField(
                        through="loans.CustomFieldValue", to="loans.loanfield"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="loan_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loans.loanfield"
            ),
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="loan_proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loans.loanproposal"
            ),
        ),
    ]
